---
resources:
- name: raindrops-mb2-git
  type: git
  source:
    uri: git@bitbucket.org:armakuni/raindrops-mb2.git
    private_key: ((git_private_key))
    branch: master

- name: http-smoke-tests-git
  type: git
  source:
    uri: https://github.com/FidelityInternational/http-smoke-tests.git

- name: pws-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf_username))
    password: ((cf_password))
    organization: armakuni
    space: moses-training

jobs:
- name: deploy-raindrops
  serial: true
  plan:
  - get: raindrops-mb2-git
    trigger: true
  - put: pws-cf
    params:
      manifest: raindrops-mb2-git/manifest.yml
      path: raindrops-mb2-git
      current_app_name: raindrops-mb2

- name: smoke-test-raindrops
  serial: true
  plan:
  - aggregate:
    - get: raindrops-mb2-git
      trigger: true
      passed:
        - deploy-raindrops
    - get: pws-cf
      passed:
        - deploy-raindrops
    - get: http-smoke-tests-git
  - task: http-smoke-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.9-alpine3.6
      inputs:
        - name: http-smoke-tests-git
          path: src/http-smoke-tests-git
      run:
        path: sh
        args:
        - -euc
        - |
          export GOPATH=$PWD
          cd src/http-smoke-tests-git
          HEADERS="{\"Authorization\": \"Basic $(printf "${SMOKE_TEST_USERNAME}:${SMOKE_TEST_PASSWORD}" | base64)\"}" \
            go test -v ./...
    params:
      RESPONSE_CODE: 200
      RESPONSE_BODY_REGEX: Pling
      URL: https://raindrops-mb2.cfapps.io/?number=3
