---
resources:
- name: raindrops-mb2-git
  type: git
  source:
    uri: git@bitbucket.org:armakuni/raindrops-mb.git
    private_key: ((git_private_key))
    branch: master

- name: pws-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf_username))
    password: ((cf_password))
    organization: armakuni
    space: moses-training

jobs:
 - name: deploy-raindrops
  serial: true
  plan:
  - get: raindrops-mb-git
    trigger: true
    passed:
      - raindrops-mb-test
  - put: pws-cf
    params:
      manifest: raindrops-mb-git/manifest.yml
      path: raindrops-mb-git
      current_app_name: raindrops-mb
